const PROFESSIONS = [
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Python Developer',
  'Ruby Developer',
  'Node.js Developer',
  'PHP Developer',
  'Java Developer',
  '.NET / C# Developer',
  'Go Developer',
  'Rust Developer',
  'iOS Developer',
  'Android Developer',
  'React Native Developer',
  'Flutter Developer',
  'DevOps Engineer',
  'Site Reliability Engineer (SRE)',
  'Cloud Engineer (AWS/GCP/Azure)',
  'Security Engineer',
  'QA Engineer (Manual)',
  'QA Automation Engineer',
  'Data Engineer',
  'Data Scientist / ML Engineer',
  'AI / LLM Engineer',
  'Database Administrator (DBA)',
  'System Architect',
  'Technical Lead',
  'Engineering Manager',
  'Product Manager',
  'Project Manager',
  'Scrum Master / Agile Coach',
  'Business Analyst',
  'UI Designer',
  'UX Designer',
  'UI/UX Designer',
  'Graphic Designer',
  'Motion Designer',
  'Technical Writer',
  'IT Recruiter',
  'Sales Engineer / Pre-Sales',
  'Other',
];

const professionOptions = PROFESSIONS.map((p) => ({
  text: { type: 'plain_text', text: p },
  value: p,
}));

const referralModal = {
  type: 'modal',
  callback_id: 'referral_modal',
  title: { type: 'plain_text', text: 'Referral a Candidate' },
  submit: { type: 'plain_text', text: 'Submit' },
  close: { type: 'plain_text', text: 'Cancel' },
  blocks: [
    {
      type: 'input',
      block_id: 'candidate_name',
      label: { type: 'plain_text', text: 'Full Name' },
      hint: { type: 'plain_text', text: 'First and last name' },
      element: {
        type: 'plain_text_input',
        action_id: 'value',
        placeholder: { type: 'plain_text', text: 'e.g. Ivan Petrov' },
      },
    },
    {
      type: 'input',
      block_id: 'candidate_email',
      label: { type: 'plain_text', text: 'Email' },
      element: {
        type: 'plain_text_input',
        action_id: 'value',
        placeholder: { type: 'plain_text', text: 'candidate@example.com' },
      },
    },
    {
      type: 'input',
      block_id: 'candidate_telegram',
      optional: true,
      label: { type: 'plain_text', text: 'Telegram' },
      element: {
        type: 'plain_text_input',
        action_id: 'value',
        placeholder: { type: 'plain_text', text: '@username' },
      },
    },
    {
      type: 'input',
      block_id: 'candidate_whatsapp',
      optional: true,
      label: { type: 'plain_text', text: 'WhatsApp' },
      element: {
        type: 'plain_text_input',
        action_id: 'value',
        placeholder: { type: 'plain_text', text: '+1234567890' },
      },
    },
    {
      type: 'input',
      block_id: 'candidate_linkedin',
      label: { type: 'plain_text', text: 'LinkedIn Profile' },
      element: {
        type: 'plain_text_input',
        action_id: 'value',
        placeholder: { type: 'plain_text', text: 'https://linkedin.com/in/username' },
      },
    },
    {
      type: 'input',
      block_id: 'candidate_profession',
      label: { type: 'plain_text', text: 'Profession' },
      element: {
        type: 'static_select',
        action_id: 'value',
        placeholder: { type: 'plain_text', text: 'Select profession' },
        options: professionOptions,
      },
    },
    {
      type: 'input',
      block_id: 'candidate_cv',
      label: { type: 'plain_text', text: 'Resume (CV)' },
      hint: { type: 'plain_text', text: 'Upload PDF, DOCX, or any file' },
      element: {
        type: 'file_input',
        action_id: 'value',
        filetypes: ['pdf', 'doc', 'docx'],
        max_files: 1,
      },
    },
    {
      type: 'input',
      block_id: 'candidate_relation',
      label: { type: 'plain_text', text: 'How do you know this candidate?' },
      element: {
        type: 'plain_text_input',
        action_id: 'value',
        multiline: true,
        placeholder: { type: 'plain_text', text: 'e.g. Former colleague at Company X, worked together for 2 years' },
      },
    },
    {
      type: 'input',
      block_id: 'candidate_comment',
      optional: true,
      label: { type: 'plain_text', text: 'Additional Comment' },
      element: {
        type: 'plain_text_input',
        action_id: 'value',
        multiline: true,
        placeholder: { type: 'plain_text', text: 'Anything else HR should know...' },
      },
    },
  ],
};

module.exports = referralModal;
